### PR TITLE
Update Gradle version to 2.11

### PR DESCRIPTION
**Pull request by cypressious**

### CODE REVIEW

**Comment by cypressious** [comment]
Hm, seems like the android plugin needs to be updated as well.

**Comment by cypressious** [comment]
If you don't want to depend on an alpha plugin, this needs to wait until plugin version 2.0.0 hits stable.

**Comment by dlew** [comment]
I purposefully don't want to depend on the alpha plugin atm.

**Comment by cypressious** [comment]
Understood. Also, Lint is unhappy with something.

**Comment by dlew** [comment]
I can add lint output to travis ci.

**Comment by cypressious** [comment]
I guess running on your local machine should be enough. I'm not familiar with this project, so I'd rather not mess with it.

**Comment by cypressious** [comment]
Also, I added the alpha plugin instead of the beta plugin.

**Comment by dlew** [comment]
I think you misunderstood me. I don't want alpha or beta. I want stable. 1.5.0.

**Comment by cypressious** [comment]
Don't worry, I understood. I just noticed that I used a completely wrong version that's neither stable nor the latest.

**Comment by dlew** [comment]
Alright, but it's on 2.0.0-alpha5 right now, not 1.5.0, which is why I was confused.

If you rebase there *should* be lint output to the console now. (Not sure if I did it right, but eh, I'm being lazy right now.)

**Comment by dlew** [comment]
Travis CI is showing why lint is failing now. New checks added in newer plugin versions.

That said - I really, really don't think you understand what I mean by 1.5.0, from looking at your comits. I don't mean 2.0.0-alpha, I don't mean 2.0.0-beta. I mean 1.5.0.

**Comment by dlew** [comment]
Also, I just double-checked and you didn't regenerate the wrapper, you just bumped the number, which isn't correct.

**Comment by cypressious** [comment]
Sorry I'm being confusing here. Plugin version `1.3.1` and `1.5.0` both don't work with Gradle >2.9 because they do the version comparison wrong. This was only fixed in version `2.0.0-alpha1`.

I just wanted to set the plugin version in my fork so that it builds at all. The first time I accidentely set it to `alpha5` instead of `beta5`. You said you wanted to depend on a stable version so my intention was to let the PR sit until it's released. When you asked me to rebase I also pushed the commit that fixed my previous error.

So, to clear any confusion: This PR is inteded to sit until `2.0.0` is released at which point I'll commit the new version number. If that's not ok for you, feel free to close it.

**Comment by cypressious** [comment]
I was under the impression that regenerating the wrapper is usually unnecessary. If you like, I'll do it anyway.

**Comment by dlew** [comment]
It's usually unnecessary, but sometimes it matters; it's worth running the actual `wrapper` command just to make sure.

I've setup #45 because it'll just be faster this way.

**Comment by cypressious** [comment]
Alright, I'll close this.

**Comment by dlew** [comment]
1.5.0 works with gradle 2.11, at least it does on my machine.

**Comment by cypressious** [comment]
You're right, I thought only 2.0.0 fixed this. Seems I was wrong.

**Pull request closed without merging**
