### PR TITLE
Remove Type enum in favor of IntDef

### PR DESCRIPTION
**Pull request by Xzan**

### CODE REVIEW

**Comment by dlew** [comment]
I should've been more clear on Twitter, but I do not consider enums to be a big performance issue.

If you can demonstrate (with benchmarks) how an app is being crippled by these enums, then I'll merge this.

**Comment by Xzan** [comment]
I understand your point of view and, in an app, on its own, I would not have taken the time to change that. But, because it's a library which may be used by a lot of applications, it means it may end up be using a significant amount of memory on the device. The more applications use this library, the more unnecessary memory will be used by the enum.
As Colt McAnlis says in his video : https://www.youtube.com/watch?v=Hzs6OBcvNQE&t=166

If you still don't agree, and it's your entire right, you can close this PR and accept my apologies for wasting your time.

**Comment by dlew** [comment]
I think the memory pressure is overblown. See this for why: https://plus.google.com/+JakeWharton/posts/bTtjuFia5wm

**Comment by Xzan** [comment]
I have been trying to get a link to Colt McAnlis' response but I wasn't able to. So, if you look at his first reply, I believe it explains quite well what he meant.

To me, the thing is, I see no added value to use an enum over IntDef here. If there was a constructor and other values linked to each element, I would be totally fine with it. Using an enum when IntDef is more suitable is going against best practices without any good reason.

Nevertheless, I would also understand that you don't want to merge this because you don't want to force people to change their code over such a little improvement but that's a legacy reason not a performance one.

**Comment by dlew** [comment]
> Using an enum when IntDef is more suitable is going against best practices without any good reason.

That is completely untrue. I take reasons **very** seriously.

I value enums because they are types, and I appreciate types very highly because they help me write more correct code. For the same reason that [Stringly typed](http://c2.com/cgi/wiki?StringlyTyped) code is bad, I find integer-typed code equally maddening.

IntDef gets you closer, but I prefer language constructs to annotations + IDE where possible. You can write code without the IDE and lose the protection; you can't dodge enums.

This blog post has a similar take as I do on enums: https://publicobject.com/2015/09/30/enumsmatter/

**Comment by Xzan** [comment]
Sorry if I offended you, I never intended to do so.

I understand your point but I don't entirely agree with you because IntDef and other annotation will trigger lint errors and fail your compilation : http://developer.android.com/tools/debugging/annotations.html. 
Yet, it's true that it's less enforcing than enum.

I can see we agree to disagree on the matter and therefore I close this PR. As I said, I don't want to waste your time on this.

**Pull request closed without merging**
